
# set new names for parameters in job to give more descriptive names
# Job = in which job this parameter should be changed (job name or all)
# Parameter = original name (as in job.star file)
# Alias = new parameter name that should be displayed
submission:
  - HeadNode: hpcl8001
    SshCommand: "ssh -X "
    Environment: "module load RELION/5.0-beta-3NC;source /fs/pool/pool-fbeck/projects/4TomoPipe/rel5Pipe/src/CryoBoost/.cbenv"
    CalusterStatus: sinfo
    Helpssh: c-wing-wiki.biochem.mpg.de/wiki/index.php/Ssh-keygen
    HelpConflict: "rmove relion/python from your .bashrc hpcl8 or global section"

aliases:

  - Job: all
    Parameter: qsubscript
    Alias: Submission Script
  - Job: all
    Parameter: qsub_extra1
    Alias: NrNodes 
  - Job: all
    Parameter: qsub_extra2
    Alias: MPIperNode
  - Job: all
    Parameter: qsub_extra3
    Alias: PartionName  
  - Job: all
    Parameter: qsub_extra4
    Alias: NrGPU
  - Job: all
    Parameter: qsub_extra5
    Alias: MemoryRAM  

# parameters have different names in header/mdoc than in Relion --> make compatible
# key = parameter name in header/mdoc file
# value = parameter name in config_aliases file (code uses that name directly to find the correct entry, avoids additional loops)

meta_data:

  header:
    - EER_number: eer grouping

  mdoc:
    - ImageSize: x dimensions
    - ImageSize: y dimensions
    - PixelSpacing: Pixel in A
    - Voltage: kV


# save the parameters that are exclusively based on the microscope used so they can automatically be filled in
# parameter-aliases are used for parameter names

microscopes:

  - Microscope: Titan Krios 4
    Parameters:
      # microscope = Titan Krios:
      - Spherical aberration: 2.7
      - kV: 300
      - q Submission Script: ../../../01-Data/relion/qsub_gpu_Relion5.sh
    

star_file:

  importmovies: importmovies/tilt_series.star
  motioncorr: motioncorr/corrected_tilt_series.star
  ctffind: ctffind/tilt_series_ctf.star
  analysetilts: feature_analysis/feature_analysis.star
  filtertilts: filtertilts/tiltseries_filtered.star
  aligntilts: aligntilts/aligned_tilt_series.star
  reconstruction: reconstruction/tomograms.star
  denoisetrain:   reconstruction/tomograms.star   #is not the result but the reconstruction is used as result   
  denoisepredict: denoise/denoised_tilt_series.star #maybe switch to reconstruction

computing:
   
  QueSize: 
      large: 5
      medium: 3
      small: 1
   
  p.hpcl8:
      NrGPU: 2
      NrCPU: 24
      RAM: 370G
  
  p.hpcl9:
      NrGPU: 4
      NrCPU: 72
      RAM: 970G

  p.hpcl93:
      NrGPU: 4
      NrCPU: 128
      RAM: 740G  
  
  NODE-Sharing:
    CPU-PerGPU: 6
    ApplyTo:
     - p.hpcl9
     - p.hpcl93

  JOBTypes:
      CPU-MPI:
       - motioncorr
       - ctffind
      GPU-OneProcess: 
        - aligntilts
      GPU-OneProcessOneGPU:
        - denoisetrain
        - denoisepredict
      GPU-ThreadsOneNode:      
        - filtertilts    
      CPU-2MPIThreads:
        - reconstruction 
  JOBMaxNodes:
        motioncorr:
         - 4          